spring.application.name=spotify-app

management.endpoints.web.exposure.include=*
#  * -> health, info, metrics, loggers prometheus
management.endpoint.health.show-details=ALWAYS
management.info.env.enabled=true

info.app.name=Spotify App
info.app.description=Spotify Rest API's